on:
    push:
        branches: [main]

jobs:
    build_and_publish_to_npm_registry:
        name: Build and publish to 'NPM Registry'
        runs-on: ubuntu-latest
        permissions:
            id-token: write

        steps:
            - uses: actions/checkout@v6
              name: Checkout repository

            - uses: oven-sh/setup-bun@v2
              name: Setup bun

            - run: bun install
              name: Install dependencies

            - uses: actions/setup-node@v4
              name: Setup 'node' and 'npm'
              with:
                  registry-url: "https://registry.npmjs.org"

            - run: pwd

            - run: echo $NPM_CONFIG_USERCONFIG

            - run: ls -la .
              name: List all files

            - run: cat .npmrc
              name: Get .npmrc file contents

            - run: echo ${{ secrets.NPM_TOKEN }} | sed "s/./&*/g; s/*$//"
              name: Test NPM_TOKEN

            - run: npm publish --provenance
              name: Publish to 'NPM Registry'
