on:
    push:
        branches: [main]

jobs:
    build_and_publish_to_npm_registry:
        name: Build and publish to 'NPM Registry'
        runs-on: ubuntu-latest
        permissions:
            id-token: write

        steps:
            - uses: actions/checkout@v6
              name: Checkout repository

            - uses: oven-sh/setup-bun@v2
              name: Setup bun

            - run: bun install
              name: Install dependencies

            - uses: actions/setup-node@v6
              name: Setup 'node' and 'npm'
              with:
                  node-version-file: .nvmrc
                  registry-url: "https://registry.npmjs.org"

            - run: npm --version
              name: Check npm version

            - run: npm publish
              name: Publish to 'NPM Registry'
